[window]
opacity = 0.9
padding.x = 2
padding.y = 2

[font]
size = 11
normal.family = "Iosevka Nerd Font Mono"
bold.family = "Iosevka Nerd Font Mono"
italic.family = "Iosevka Nerd Font Mono"
bold_italic.family = "Iosevka Nerd Font Mono"
